[package]
name = "framework-crate"
version = "0.2.0"
edition = "2024"
authors = ["Vincent Chang"]
license = "MIT"

[dependencies]
iced = { version = "0.14", default-features = false, features = [
    "wgpu",
    "tokio",
    "canvas",
    "advanced",
] }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "time",
    "macros",
    "sync",
] }
serde = { version = "1", features = ["derive"] }
toml = "1"
framework_lib = "0.6.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "6"
core_affinity = "0.8"
parking_lot = "0.12"
windows-sys = { version = "0.61.2", features = [
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Storage_FileSystem",
    "Win32_System_LibraryLoader",
] }
sha2 = "0.10"

[build-dependencies]
winresource = "0.1"
png = "0.17"

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
